#!/usr/bin/env python3
# Generated by Chatgaiya++ compiler

def _cg_charat(s, i):
    try:
        return s[i]
    except (IndexError, TypeError):
        return ""

s = input()
U = "LEADINGUNIVERSITY"
u = "leadinguniversity"
ans = ""
i = 0
j = 0
while (((i < 17)) and ((j < 17))):
    if (((_cg_charat(s, i) == _cg_charat(U, j))) or ((_cg_charat(s, i) == _cg_charat(u, j)))):
        ans = (ans + _cg_charat(s, i))
        j += 1
    i += 1
print(ans)
